train_file: ['/COVID_8TB/sangjoon/mimic_CXR/cxr.h5', '/COVID_8TB/sangjoon/mimic_CXR/mimic_impressions_final.csv']
val_file: '/home/depecher/PycharmProjects/TCL_local/data/mimic/Valid.jsonl'
test_file: '/home/depecher/PycharmProjects/TCL_local/data/mimic/Test.jsonl'

# each train_file (json) contains a python list where each item is {'image': img_path, 'caption': text or list_of_text }               
bert_config: 'configs/config_bert.json'
fusion_config: 'configs/config_fusion.json'

image_res: 224
vision_width: 768
embed_dim: 256
batch_size: 8
batch_size_test: 1
temp: 0.07
mlm_probability: 0.15
queue_size: 32768
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 15, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}

# iBOT specific options
patch_size: 16
out_dim: 8192
patch_out_dim: 8192
shared_head: True
shared_head_teacher: True
norm_last_layer: False
norm_in_head: None
act_in_head: 'gelu'
use_masked_im_modeling: True
pred_ratio: 0.3
pred_ratio_var: 0.
pred_shape: 'block'
pred_start_epoch: 1
lambda1: 1.0
lambda2: 1.0
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_patch_temp: 0.04
teacher_patch_temp: 0.07
warmup_teacher_temp_epochs: 3
use_fp16: False
clip_grad: 3.0
drop_path: 0.1
freeze_last_layer: 1
global_crops_scale: [0.5, 1.0]
local_crops_scale: [0.2, 0.5]
global_crops_number: 2
local_crops_number: 8

