candidate_file: '/8TB_hdd/downloads/convirt-master/text-retrieval/candidate.csv'
query_file: '/8TB_hdd/downloads/convirt-master/text-retrieval/query.csv'
test_file: '/8TB_hdd/rsna-pneumonia-detection-challenge/test.csv'
image_root: None

bert_config: 'configs/config_bert.json'

image_res: 224
batch_size_train: 16
batch_size_test: 1

queue_size: 81920
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 50

alpha: 0.4
distill: True
warm_up: True

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-6, warmup_epochs: 1, cooldown_epochs: 0}

patch_size: 16
out_dim: 8192
patch_out_dim: 8192
shared_head: False
shared_head_teacher: True
norm_last_layer: True
norm_in_head: None
act_in_head: 'gelu'
lambda1: 1.0
lambda2: 1.0
warmup_teacher_temp: 0.04
teacher_temp: 0.04
warmup_teacher_patch_temp: 0.04
teacher_patch_temp: 0.07
warmup_teacher_temp_epochs: 3
use_fp16: False
clip_grad: 3.0
drop_path: 0.1
freeze_last_layer: 1
global_crops_scale: [0.5, 1.0]
local_crops_scale: [0.2, 0.5]
global_crops_number: 2
local_crops_number: 8
n_last_layer: 1
fp16_scaler: False


